name: ibilling
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.0.0
  get_it: ^8.0.3
  sizer: ^3.0.5
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  intl: ^0.20.2
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.11
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/translations/
    - assets/icons/selected/
    - assets/icons/unselected/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600