// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKcsfW5Qg5YlLx5pY870CzlJcYt7bhCUc',
    appId: '1:255827182732:web:7e7bbcf414388a2a1a27a9',
    messagingSenderId: '255827182732',
    projectId: 'ibilling-9961c',
    authDomain: 'ibilling-9961c.firebaseapp.com',
    storageBucket: 'ibilling-9961c.firebasestorage.app',
    measurementId: 'G-DSZVJ4P9N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreX4qp27L_zTA_JJUF3GsRJWvKxiyvDc',
    appId: '1:255827182732:android:5d5e0af17ee1e72e1a27a9',
    messagingSenderId: '255827182732',
    projectId: 'ibilling-9961c',
    storageBucket: 'ibilling-9961c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfM_teXjKesoRFrf08Cp_Zh4jf6GGFYtM',
    appId: '1:255827182732:ios:0d497e8dcd2455e11a27a9',
    messagingSenderId: '255827182732',
    projectId: 'ibilling-9961c',
    storageBucket: 'ibilling-9961c.firebasestorage.app',
    iosBundleId: 'com.ibilling.ibilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfM_teXjKesoRFrf08Cp_Zh4jf6GGFYtM',
    appId: '1:255827182732:ios:0d497e8dcd2455e11a27a9',
    messagingSenderId: '255827182732',
    projectId: 'ibilling-9961c',
    storageBucket: 'ibilling-9961c.firebasestorage.app',
    iosBundleId: 'com.ibilling.ibilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKcsfW5Qg5YlLx5pY870CzlJcYt7bhCUc',
    appId: '1:255827182732:web:cc78046d4c24217a1a27a9',
    messagingSenderId: '255827182732',
    projectId: 'ibilling-9961c',
    authDomain: 'ibilling-9961c.firebaseapp.com',
    storageBucket: 'ibilling-9961c.firebasestorage.app',
    measurementId: 'G-CBCT4ZVQFD',
  );
}
